//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicEvent
    {
        public string Title { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public string Place { get; set; }
        public string FullName { get; set; }
        public int EventID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Private { get; set; }
    }
}
